import { useState, useMemo } from 'react';
import { useFinancial } from '../contexts/FinancialContext';
import { useFinancialSummary } from '../hooks/useFinancialSummary';
import { useChartData } from '../hooks/useChartData';
import { useOpenFinance } from '../hooks/useOpenFinance';
import { useProductionMode } from '../hooks/useProductionMode';
import { useGoals } from '../contexts/GoalsContext';
import { loadSampleData } from '../utils/sampleData';
import { createTestCSVFile, createTestNubankCSVFile, createTestRecargaPayCSVFile } from '../utils/testImportData';
import { useImport } from '../hooks/useImport\';ort\';Import\';Import\';t\';oks/useImport';
